[package]
name = "Computress"
version = "0.1.0"
authors = ["OpenFusion Contributors"]
edition = "2021"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.6"
poise = "0.6.1"
tokio = { version = "1.42.0", features = ["full"] }
